### ISSUE TITLE
Seleção de campo de estado

### ISSUE THREAD

**Issue by ren4ndev** [baymabruno/autocompletar-endereco-woocommerce#3]
Olá @baymabruno 

Não entendi por que a seleção do campo de estado foi feita assim:

```js
$("#select2-billing_state-container").val(dados.uf);
$("#select2-billing_state-container").html(dados.uf);
$("#select2-billing_state-container").prop("title", dados.uf);
```

E não assim:

```js
$('#billing_state option[value="' + dados.uf + '"]').attr('selected', 'selected').change();
```

**Comment by baymabruno** [comment]
Olá @ren4ndev é que no tema que eu estava utilizando só funcionou desse jeito, só pelo campo selected não estava exibindo corretamente para o usuário
